const cheerio = require('./methods/cheerio');
const get = require('./methods/get');
const post = require('./methods/post');
const setHeaders = require('./methods/setHeaders');
const find = require('./methods/find');
const giveWorker = require('./methods/giveWorker');
const retries = require('./methods/retries');
const store = require('./methods/store');
const pushTo = require('./methods/pushTo');
const execute = require('./methods/execute');
const setProxies = require('./methods/setProxies');
const setWorkers = require('./methods/setWorkers');
const run = require('./methods/run');
const selenium = require('./methods/selenium');
const setInterval = require('./methods/setInterval');
const setAuth = require('./methods/setAuth');
const crawler = require('./methods/crawler');
const notify = require('./methods/notify')

module.exports = { cheerio, get, post, setHeaders, find, retries, store, pushTo, execute, setProxies, setWorkers, giveWorker, run, selenium, setInterval, setAuth, crawler, notify };
